import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Menu from "@/components/Menu";
import Hero from "@/components/Hero";
import Features from "@/components/Features";
import QuotoCard from "@/components/QuotoCard";
import Meeting from "@/components/Meeting";
import Count from "@/components/Count";
import SocialProof from "@/components/SocialProof";
import CallFeatures from "@/components/CallFeatures";



export default function Home() {
  return (
    <>
      <Head>
        <title>teach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Neto Russo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Menu />
      </header>
      <main className={styles.main}>
        <Hero />
        <Features />
        <QuotoCard />
        <Meeting />
        <Count />
        <SocialProof />
        <CallFeatures />
      </main>
    </>
  );
}
