import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Menu from "@/components/Menu";


export default function Home() {
  return (
    <>
      <Head>
        <title>Teach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Neto Russo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Menu />
      </header>
    </>
  );
}
